owner: abelazo # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Abelazo Photography
    url: https://abelazo.photography

assignees: # Users to assign downtime issues (optional)
  - abelazo

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Abelazo's Upptime
  introTitle: "Abelazo's monitor and status page."
  introMessage: Status page which uses **real-time** data from my [GitHub repository](https://github.com/abelaso/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
